version: '3.1'

services:
  postgres:
    image: postgres
#  restart: always
    environment:
     - POSTGRES_PASSWORD=postgress
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 1234:5432

